- LICENSE
- README.md
Related https://github.com/lightblue-platform/lightblue-core/issues/190
> Lincense branch

- manifests/service/plugin/rdbms.pp
- templates/lightblue-rdbms-datasource.conf.erb
Only create one datasource for now, will refactor in the future to handle multiple
> Add rdbms.pp back

- hieradocs.sh
- manifests/eap.pp
It's based on documentation on classes.  It could be better but it's "good enough" for now.
> Fixes #25: added script to generate hiera key documentation

- .fixtures.yml
- .gitmodules
- .travis.yml
- spec/classes/lightblue/eap/logging_spec.rb
- spec/classes/lightblue/eap/module_spec.rb
- spec/classes/lightblue/eap/mongossl_spec.rb
- spec/classes/lightblue/eap/ssl_spec.rb
- spec/fixtures/hiera/repo.yaml
For various classes.  Will move back to in progress until it's ready.
> Add basic class tests

- manifests/application/datamgmt.pp
- spec/classes/lightblue/application/datamgmt_spec.rb
- spec/fixtures/hiera/repo.yaml
...to reflect changes in
https://github.com/lightblue-platform/lightblue-applications/pull/54
Namely, the server-side client configuration is no longer used / needed.
In addition, I added specs and fixed some bugs.
> Update datamgmt puppet class

- .travis.yml
- manifests/application/migrator.pp
- manifests/client/configure.pp
- spec/classes/lightblue/application/migrator_spec.rb
- spec/defines/lightblue/client/configure_spec.rb
these are fairly standard puppet checks we should be running.
> add syntax and lint checks

- manifests/service/plugin/statsd.pp
- spec/classes/lightblue/service/plugin/statsd_spec.rb
Essentially a duplication of the graphite puppet file and spec tests.
> fixes #93 - add statsd plugin (similar to graphite)

- manifests/client/configure.pp
- spec/defines/lightblue/client/configure_spec.rb
> lint fixes

- manifests/application/migrator.pp
- spec/classes/lightblue/application/migrator_spec.rb
> fix package name

- manifests/application/migrator.pp
> fix class path

- manifests/service/data.pp
- manifests/service/metadata.pp
enable the statsd plugin for crud and metadata.
> enable statsd plugin

- manifests/application/migrator.pp
- manifests/application/migrator/daemon.pp
- spec/classes/lightblue/application/migrator/daemon_spec.rb
- templates/application/migrator/lightblue-migrator-daemon.sh.erb
This will allow us to increase the memory given to the service
> add ability to configure jvm options

- manifests/application/migrator.pp
> minor changes

- templates/web-connector.conf.erb
This improves cert authentication performance greatly (by 1s).
> Setting verify-client=want on the https connector

- manifests/application/migrator.pp
We have a need to be able to modify the package name
> make migrator package name a param

- spec/classes/lightblue/application/migrator_spec.rb
- spec/classes/lightblue/eap/logging_spec.rb
Somebody didn't run their unit tests before merging.
> remove job_version

- manifests/eap/module.pp
- manifests/eap/module/datasources.pp
- templates/properties/datasources.json.erb
Fixed extra } that came from incorrectly closed rdbms block
> Added way to set readPreferences for mongo metadata and data datasources

- manifests/java.pp
It was broken and causing errors.  I simplified it to set the config for all the various alternatives to 'auto' if not already set to auto.
> Fix java alternative

- manifests/java.pp
> lint changes

- manifests/application/migrator/log4j.pp
- templates/application/migrator/log4j.properties.erb
Done by @bserdar internally, I'm just pushing upstream.
> Add inconsistency log

- manifests/eap/ssl.pp
- manifests/eap/ssl_keystore_file.pp
- manifests/eap/truststore.pp
- manifests/eap/truststore_file.pp
- spec/defines/lightblue/eap/ssl_file_spec.rb
- spec/defines/lightblue/eap/ssl_keystore_file_spec.rb
- spec/defines/lightblue/eap/truststore_file_spec.rb
- spec/fixtures/hiera/repo.yaml
to keystores and truststores.  Fixes #188
> Add support for adding multiple certificates

- manifests/application/healthcheck_client.pp
Somehow this part didn't make it into the last PR.  @dcrissman can you have a look when you have the chance?  Thanks
> Actually create client certificate files

- manifests/application/healthcheck.pp
- templates/properties/modulehealthcheckclient.xml.erb
Sorry @dcrissman I missed one more commit in the original PR
> Add healthcheck client ERB

- manifests/authentication/certificate.pp
- templates/lightblue-security-domain-cert.conf.erb
This is the Puppet change that corresponds to https://github.com/lightblue-platform/lightblue-rest/pull/248
> Add environment parameter to cert auth security domain

- manifests/application/healthcheck.pp
- manifests/application/healthcheck_client.pp
- manifests/application/metadatamgmt.pp
- manifests/eap/client.pp
- manifests/eap/client_ca_cert_file.pp
- manifests/eap/ssl.pp
- manifests/eap/truststore.pp
WIP: Fixing puppet lint issues.
> oh, lint and spacing

- templates/logging.conf.erb
> Only keep 10 server log rotations

- manifests/authentication/certificate.pp
- templates/properties/ldap-healthcheck-config.json.erb
> WIP: Added template for LDAP configuration for health check

- manifests/eap.pp
- templates/standalone.conf.erb
https://github.com/lightblue-platform/lightblue-core/pull/795 needs to be merged first.
> Stopwatch configuration

- manifests/eap/module.pp
- templates/properties/lightblue-crud.json.erb
Configs for https://github.com/lightblue-platform/lightblue-core/pull/801
> Adding maxResultSetSizeB and warnResultSetSizeB properties

- templates/application/migrator/lightblue-migrator-daemon.sh.erb
- templates/client/lightblue-client.properties.erb
- templates/properties/config.properties.erb
- templates/properties/datasources.json.erb
- templates/properties/lightblue-crud.json.erb
- templates/web-connector.conf.erb
@alechenninger @kahoali can one of you review/merge when you have the chance?
> Fix deprecated syntax

- manifests/service/plugin/graphite.pp
- manifests/service/plugin/statsd.pp
@kahoali please review at your earliest convenience
> Fix variable usage in inline templates
